---
- name: clone app from github
  git: 
    repo: 'https://github.com/mbaran0v/python-sample-app'
    dest: "/home/{{ deployer_user }}/{{ app_name }}"
    update: yes
  
- name: Recursively change ownership of a directory
  file:
    path: "/home/{{ deployer_user }}/{{ app_name }}"
    state: directory
    recurse: yes
    owner: "{{ deployer_user }}"
    group: "{{ deployer_user }}"
    mode: '0755'
